### ISSUE TITLE
Is the data passed into Unity in Python 21 points?

### ISSUE THREAD

**Issue by l1uw3n** [imadeddinedjekoune/Hand-Detection-3D#1]
Hello, I have looked at your project and cannot find the code for Python to pass in data. May I ask if Python passes in the coordinates of 21 points? Passing to port 5052?

**Comment by imadeddinedjekoune** [comment]
Hello,

Thank you for taking the time to review the project. Apologies for the oversight in not including the Python code responsible for passing in the coordinates of 21 points to port 5052. The focus was primarily on the 3D hand implementation and rigging.

The Python code used for detecting and tracking the hand, as well as sending the data via the network, is built on the foundation provided by the YouTuber @murtazahassan, I'd like to give credit to their work for this part of the project , here is the full video : 
[Full Tutorial](https://www.youtube.com/watch?v=RQ-2JWzNc6k)

### for the source code : 
**Main.py**
```python
from cvzone.HandTrackingModule import HandDetector
import cv2
import socket

cap = cv2.VideoCapture(0)
cap.set(3, 1280)
cap.set(4, 720)
success, img = cap.read()
h, w, _ = img.shape
detector = HandDetector(detectionCon=0.8, maxHands=2)

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
serverAddressPort = ("127.0.0.1", 5052)

while True:
    # Get image frame
    success, img = cap.read()
    # Find the hand and its landmarks
    hands, img = detector.findHands(img)  # with draw
    # hands = detector.findHands(img, draw=False)  # without draw
    data = []

    if hands:
        # Hand 1
        hand = hands[0]
        lmList = hand["lmList"]  # List of 21 Landmark points
        for lm in lmList:
            data.extend([lm[0], h - lm[1], lm[2]])

        sock.sendto(str.encode(str(data)), serverAddressPort)

    # Display
    cv2.imshow("Image", img)
    cv2.waitKey(1)
```

**HandTracking.cs**
```csharp
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class HandTracking : MonoBehaviour
{
    // Start is called before the first frame update
    public UDPReceive udpReceive;
    public GameObject[] handPoints;
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        string data = udpReceive.data;

        data = data.Remove(0, 1);
        data = data.Remove(data.Length-1, 1);
        print(data);
        string[] points = data.Split(',');
        print(points[0]);

        //0        1*3      2*3
        //x1,y1,z1,x2,y2,z2,x3,y3,z3

        for ( int i = 0; i<21; i++)
        {

            float x = 7-float.Parse(points[i * 3])/100;
            float y = float.Parse(points[i * 3 + 1]) / 100;
            float z = float.Parse(points[i * 3 + 2]) / 100;

            handPoints[i].transform.localPosition = new Vector3(x, y, z);

        }
    }
}
```

**LineCode.cs**
```csharp
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LineCode : MonoBehaviour
{

    LineRenderer lineRenderer;

    public Transform origin;
    public Transform destination;

    // Start is called before the first frame update
    void Start()
    {
        lineRenderer = GetComponent<LineRenderer>();
        lineRenderer.startWidth = 0.1f;
        lineRenderer.endWidth = 0.1f;
    }

    // Update is called once per frame
    void Update()
    {
        lineRenderer.SetPosition(0, origin.position);
        lineRenderer.SetPosition(1, destination.position);
    }
}
```

I'll make sure to update the repository promptly with the Python code to provide a clearer understanding of the data passing process.

Thank you once again for your feedback and patience.

Best regards,
Djekoune Imad Eddine .

**Comment by l1uw3n** [comment]
I am now able to run successfully. Thank you for your answer. I have benefited a lot from your ideas, but I have also noticed some issues, such as the inability to reverse the palm and the inability to move the thumb. I am not sure if it is due to the lack of bone binding. I look forward to your future updates on the project. Thank you.

**Comment by imadeddinedjekoune** [comment]
Thank you for your comprehensive review and constructive feedback regarding the project's functionality.

The challenge encountered with thumb movement stemmed from the dynamic nature of the data acquired from the OpenCV points. The rapid and often imprecise alterations in these key points presented difficulties in accurately calculating the required angles in a three-dimensional space to articulate the hand fingers bones within Unity.

To elucidate the process, the data obtained from OpenCV points served as the foundation. This data was then utilized to calculate angles in the three-dimensional space, then applying those angles to the bones hands for unity representation. Unfortunately, due to the swift and sometimes erratic changes in these key points, achieving stable and accurate thumb movements became a considerable challenge.

![testhand](https://github.com/imadeddinedjekoune/Hand-Detection-3D/assets/75379150/2cf41abf-bdeb-4e22-8dc6-cab81c9fec7c)


In attempts to mitigate this issue, I implemented various approaches, including the integration of algorithms like Moving Average (SMA) and Kalman filters to smooth it out. Despite these efforts, the inherent instability in the data persisted, resulting in an unstable and jittery representation of the hand's finger movements within the Unity environment.

Understanding the significance of precise and smooth thumb movement for an authentic representation, I am committed to further exploration and refinement of methodologies to address this challenge in future updates. Your observations are incredibly valuable, and I deeply appreciate your patience and understanding.

Best regards,
Djekoune Imad Eddine .

**Comment by l1uw3n** [comment]
Thank you for your patient answer. I have also tried to use ik to limit movement postures to make hand movements more natural, but this seems to be a difficult task and I have not found relevant research. Anyway, thank you for your generous answer.
